### PR TITLE
Add continuous integration on appveyor

### PR DESCRIPTION
**Pull request by clembou**
this PR sets up continuous testing on appveyor

I had to move the tests I found to a separate folder so that I could tell nose to only run them. That is because currently running `nosetests` at the repo root triggers unexpected side effects (some test gui code gets imported and run).

I disabled a few tests that look incorrect , and fixed the `MarmanderPowerCurveInterpolator` one that was failing.

I also disabled testing on python 3 for now but it can be easily added back by commenting out the python 3 section on the appveyor config file.

I can setup linux testing on travis too afterwards, because why not?

now we just need more tests :smile:

### CODE REVIEW

**Comment by clembou** [comment]
I have now added new end to end tests that run the benchmarks as nose tests.

These are a bit slow so I tagged them with the `slow` attribute.

To exclude them from a test run, you can use the following command:
`nosetests -a "!slow"` tests

**Comment by peterdougstuart** [comment]
Great work climb you are a hero and an example to us all...

**Comment by clembou** [comment]
either that or I have too much time on my hands!  😜 

I think you might need to login on appveyor to activate it on the root repo:
https://ci.appveyor.com/
It should pickup the config file and run things automatically from then on.

Once setup, we'll need to change the badge on the home page to point to your repo instead of my fork, e.g. to builds that will run here: https://ci.appveyor.com/project/peterdougstuart/pcwg

Also, a nice improvement would be to make appveyor create release packages for you and deploy tagged commits to github releases automatically:
https://www.appveyor.com/docs/deployment/github/

**Comment by lcameron05** [comment]
As of d3b6099bbe0ac96df74b12f367f087cb2e9f1ae9 this is now running for the [peterdougstuart/master](https://github.com/peterdougstuart/PCWG) on AppVeyor as opposed to @clembou's  fork.  Already it is proving its worth as you can see the build is failing highlighting some problems with the code which we will need to look into:
https://ci.appveyor.com/project/lcameron05/pcwg

**Pull request merged**
